# NOTE copie de base/whoami/release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whoami7
  namespace: whoami-flux
spec:
  chart:
    spec:
      chart: whoami
      sourceRef:
        kind: HelmRepository
        name: whoami
  interval: 50m
  install:
    remediation:
      retries: 3