apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whoami6
  namespace: whoami-flux
spec:
  chart:
    spec:
      chart: whoami
      sourceRef:
        kind: HelmRepository
        name: cowboysysop
  interval: 50m
  install:
    remediation:
      retries: 3

